# Generated by Django 5.2.8 on 2026-01-20 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_categoria_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='detalle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devolucion', to='store.detalleorden'),
        ),
    ]
