# Generated by Django 5.2.8 on 2026-01-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_carritoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarritoItem',
        ),
    ]
