# Generated by Django 5.2.8 on 2026-01-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Razón por la cual se rechazó la devolución', null=True),
        ),
    ]
